### ISSUE TITLE
IntranetUserJS: Restrict patron modification by category

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-restrict-patron-modification#1]
Konfiguroitava Javascript-Plugin IntranetUserJS: Restrict patron modification by category testattavissa nexteillä.

"Rajaa tiettyjen asiakastyyppien muokkaamisen vain superlibrarian-oikeudelle (estää virkailijoita muuttamasta määritetyn käyttäjän etunimeä, sukunimeä ja kirjastokortin numeroa ja luomasta uusia määritettyä tyyppiä olevia käyttäjiä ja muuttamasta olemassa olevia käyttäjiä näiksi tyypeiksi). "

Testaus:

Jos kimpassasi on käytetty rimpsua tiketistä https://github.com/KohaSuomi/Koha/issues/1347, poista se käytöstä intranetUserJS-järjestelmäasetuksesta.

Määrittele rajoitettavat asiakastyypit pluginin määrittely-osiossa ja aktivoi plugin.

Tarkista, että rajoitukset toimivat muilla, kuin superlibrarian-oikeuksilla kuten pluginin kuvauksessa.

**Comment by MikkoLiimatainen** [comment]
Huomasin, että tallennus tyhjentää korttinumeron, kun kyseinen kenttä on disabloitu. Jostain syystä tuo ei tullut testailussani eteen tai en vain huomannut asiaa. Täytyy varmaan tarkistaa testi ja next puuttuvien korttinumeroiden varalta. Jos tälle ei muuta korjausta löydy, niin korvaamalla cardnumber-disabloinnin tällä
```javascript
$('input#cardnumber').css('pointer-events','none').attr('tabindex','-1');
``` 
näyttäisi saavutettavan sama efekti kentän suojauksesta ilman tallennuksen ongelmaa. Kenttä ei tällä tavalla näytä lukitulta, mikä voi olla hämmentävää käyttäjälle.

Sinällään erikoista, että sama ei käy muiden disabloitujen kenttien kanssa. Voisiko tuossa tallennuksessa olla jotain, mikä vaikuttaisi tähän?

**Comment by lmstrand** [comment]
Ilmeisesti jokin rikkoo samalla hetun tallennuksen/ohittamisen pakollisuuden myös. Taitaa olla tuo puhelinnumeroiden validointiskripti. En kyllä keksi syytä, että miksi korttinumero tyhjenee.

**Comment by lmstrand** [comment]
Omassa kehitysympäristössäni tuo hetun ohitus/tallennus toimii oikein tämän pluginin kanssa. Tuohon tallennukseen ei kyllä kannata tehdä kooditasolla mitään muutosta ja luulen, että ongelma on siellä. Lisään pluginiin tuon cardnumber-disabloinnin.

**Comment by MikkoLiimatainen** [comment]
Vaskissa ajateltiin ja tiistain pääkäyttäjäpalaverissakin ehdotin, että nuo estetyt kentät myös piilotettaisiin .hide()-efektillä. Eihän näitä käyttäjän tarvitse nähdäkään, jos muokkaamaan ei pysty ja samalla tulisi yksi lisäkerros suojausta.

**Comment by lmstrand** [comment]
Tuohon kenttään toimii readonly-parametri eikä korttinumero enää häviä tallennettaessa. Sitä voisi kyllä käyttää, vaikka noihin muihinkin varmuuden vuoksi (jos kentät halutaan näyttää).

$('input#cardnumber').prop("readonly", true);

**Comment by lmstrand** [comment]
Tuon kenttien piilottamisen kokonaan voisi tehdä konfiguroitavaksi. Kuvittelisin, että niiden näkymiseen voi hyvinkin olla tarvetta joissain tapauksissa.

**Comment by lmstrand** [comment]
Tein tuon readonly-muutoksen nexteille.

**Comment by MikkoLiimatainen** [comment]
Juu, tuo readonly kuulostaisi hyvältä vaihtoehdolta ja tosiaan mielellään näkisin kaikkiin kenttiin käytettävän sellaista estoa, jonka ei ole todettu tiputtavan kentistä sisältöjä. Testasin tätä muutosta ja minusta tuo toimii nyt hyvin, eikä tietoja enää pudonnut tallennettaessa.

Myös kenttien piilotuksen parametrointi kuulostaa hyvältä, niin kimpat voivat itse päättää kuinka haluavat plugaria käyttää.

Sitä mietin, kun tuossa piilotetaan asiakasta luotaessa nuo käyttäjätyyppivalinnan ryhmät, joihin valitut käyttäjätyypit kuuluvat, niin se pitäisi varmaan muuttaa niin, että piilotetaan ne käyttäjätyypit ja sitten voisi toisella parametrilla piilottaa ne ryhmäotsikotkin halutessaan. Nyt on mahdollista, että menee sellainenkin otsikkotaso piiloon, jossa olisi muokattavissa oleva käyttäjätyyppi.

**Comment by pknuuti** [comment]
Vaaran nextillä testattu poistamalla IntranetUserJS-asetuksella määritelty esto muokkaukseen ja aktivoimalla ja ottamalla käyttöön tämä plugari. Toimii siten, että ei-superlibrarian ei pysty muokkaamaan VIRKAILIJA-tunnuksella olevan henkilön sukunimeä, etunimeä tai kirjastokortin numeroa eikä myöskään valitsemaan tätä asiakastyyppiä uudelle tai muokattavalle henkilölle.

**Comment by piiaseme** [comment]
OUTIn nextillä testattu. Rajoitukset toimivat muilla, kuin superlibrarian-oikeuksilla. Superlibrarian-oikeuksilla voi tehdä ja muokata tunnuksia kuten ennenkin.

**Comment by Tuomas-Kyyti** [comment]
Kyytin nextillä otettu käyttöön ja testattu.

**Comment by ReettaSiili** [comment]
Skripti ei ollut ennestään Siilissä käytössä mutta nyt plugari on nextillä ja toimii.

**Comment by MikkoLiimatainen** [comment]
Vaskissa otettu plugari nextillä käyttöön ja se toimii.

**Comment by AnneliO** [comment]
**Kommentoi** tikettiä, kun liitännäinen on otettu käyttöön. Seuranta kimpoista, joissa plugari on otettu nextillä käyttöön:

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by ElinaUotila** [comment]
Kirkesissä otettu käyttöön ja testattu toimivaksi.

**Comment by LeenaKinnunen** [comment]
Lapissa laitettu käyttöön asiakaslajeille VIRKAILIJA,AUTOMAATTI,API.

Toiminnossa on virhe: Jos perusvirkailijatunnuksella käy muuttamassa toisen virkalijatunnuksen kotikirjastoa, osoitetta, varaustunnistetta tai muita muokattavia kenttiä, kyseinen tunnus muuttuu vanhentuneeksi, vanhenemispäiväksi tulee 27.04.2024.

**Comment by lmstrand** [comment]
Tätä ongelmaako ei ole, jos plugin ei ole käytössä?

**Comment by LeenaKinnunen** [comment]
Hyvä huomio, sama toistuu jos otan pluginin pois käytöstä. Testastin saman tuotannossa, ja siellä toinen tunnus ei vanhene.

**Comment by Kati-Helle** [comment]
Helle-nextissä plugin nyt käytössä. (IntranetUserJS-rimpsu ei ole ollut käytössä.)

Liittyen Hellen asiakastyyppeihin VIRKAILJA, API, AUTOMAATTI
ei-superlibrarian käyttäjätunnuksella kirjautunut ei voi muokata kenttiä
- Sukunimi
- Etunimi
- Kirjastokortin numero

Uutta asiakastietoa lisätessä ko. asiakastyypit eivät ole valittavissa
![Image](https://github.com/user-attachments/assets/e6fae7f0-f30f-4ab7-9170-059390c7932e)

Olemassa olevan asiakastiedon muokkauksen asiakastyyppivalinnoissa ko. asiakastyypit eivät ole valittavissa
![Image](https://github.com/user-attachments/assets/76740e64-589b-4163-84af-41da6c68a3c5)

**Comment by LastuJanneS** [comment]
Lastu kuittaa tehdyksi ja toimivaksi

**Comment by Hanna-Lumme** [comment]
Lumpeissa ei toistaiseksi tätä oteta käyttöön.

**Comment by AnneliO** [comment]
Kaikki kimpat kuitanneet, joten suljen tiketin. :)
